name: driver
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  intl: ^0.17.0
  percent_indicator: ^4.2.2
  flutter_phoenix: ^1.0.0
  flutter_bloc: ^8.0.1
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  flutter_local_notifications: ^9.5.3+1
  firebase_messaging: ^11.4.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  toast: ^0.3.0
  http: ^0.13.1
  image_picker: ^0.8.5+3
  shimmer_animation: ^2.1.0+1
  flutter_html: ^2.2.1
  whatsapp_unilink: ^2.0.1+1
  url_launcher: ^6.1.2
  share: ^2.0.4
  infinite_scroll_pagination: ^3.1.0
  signature: ^5.0.1
  google_maps_flutter: ^2.1.5
  location: ^4.4.0
  #  geocoder: ^0.2.1
  awesome_notifications: ^0.6.21
  dio: ^4.0.6
  path_provider: ^2.0.10
  geolocator: ^8.2.1
  permission_handler: ^9.2.0
  # TODO: Remove this branch after official release with the fix is published
  background_location:
    git:
      url: https://github.com/hilalbaig/background_location.git
      ref: master
  wakelock: ^0.6.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  change_app_package_name: ^1.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Bold.ttf
  assets:
    - assets/